In [1]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [ ]:
env = gym.make("FrozenLake-v0")

In [ ]:
actions = env.action_space.n
states = env.observation_space.n
print(states, actions)

In [ ]:
q_table = np.zeros((states, actions))
print(q_table)

In [ ]:
episodes = 10000
steps_per_episode = 100
learning_rate = 0.1
discount_rate = 0.99
exploration_rate = 1
max_rate = 1
min_rate = 0.01
decay = 0.001

In [ ]:
total_rewards = []

# Q-learning algorithm
for episode in range(episodes):
    state = env.reset()
    done = False
    current_reward = 0
    
    for step in range(steps_per_episode):
        exploration_threshold = random.uniform(0,1)
        if exploration_threshold > exploration_rate:
            action = np.argmax(q_table[state, :])
        else:
            action = env.action_space.sample()
        
        new_state, reward, done, info = env.step(action)
        
        q_table[state, action] = q_table[state, action] * (1- learning_rate) + learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))
        state = new_state
        current_reward += reward
        
        if done == True:
            break
        
    # Exploration decay
    exploration_rate = min_rate + (max_rate - min_rate) * np.exp(-decay * episode)
        
    total_rewards.append(current_reward)

thousand_rewards = np.split(np.array(total_rewards), episodes/1000)
count = 1000
print("Average reward per 1000 episodes \n")
for i in thousand_rewards:
    print("{} : {}".format(count, str(sum(i/1000))))
    count += 1000

print("\nQ-table\n")
print(q_table)

In [17]:
total_rewards = []

# Q-learning algorithm
for episode in range(episodes):
    state = env.reset()
    done = False
    current_reward = 0
    
    for step in range(steps_per_episode):
        exploration_threshold = random.uniform(0,1)
        if exploration_threshold > exploration_rate:
            action = np.argmax(q_table[state, :])
        else:
            action = env.action_space.sample()
        
        new_state, reward, done, info = env.step(action)
        
        q_table[state, action] = q_table[state, action] * (1- learning_rate) + learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))
        state = new_state
        current_reward += reward
        
        if done == True:
            break
        
    # Exploration decay
    exploration_rate = min_rate + (max_rate - min_rate) * np.exp(-decay * episode)
        
    total_rewards.append(current_reward)

thousand_rewards = np.split(np.array(total_rewards), episodes/1000)
count = 1000
print("Average reward per 1000 episodes \n")
for i in thousand_rewards:
    print("{} : {}".format(count, str(sum(i/1000))))
    count += 1000

print("\nQ-table\n")
print(q_table)

In [8]:
actions = env.action_space.n
states = env.observation_space.n
print(states, actions)

16 4


In [7]:
q_table = np.zeros((states, actions))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [19]:
episodes = 10000
steps_per_episode = 100
learning_rate = 0.1
discount_rate = 0.99
exploration_rate = 1
max_rate = 1
min_rate = 0.01
decay = 0.001

In [24]:
total_rewards = []

# Q-learning algorithm
for episode in range(episodes):
    state = env.reset()
    done = False
    current_reward = 0
    
    for step in range(steps_per_episode):
        exploration_threshold = random.uniform(0,1)
        if exploration_threshold > exploration_rate:
            action = np.argmax(q_table[state, :])
        else:
            action = env.action_space.sample()
        
        new_state, reward, done, info = env.step(action)
        
        q_table[state, action] = q_table[state, action] * (1- learning_rate) + learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))
        state = new_state
        current_reward += reward
        
        if done == True:
            break
        
    # Exploration decay
    exploration_rate = min_rate + (max_rate - min_rate) * np.exp(-decay * episode)
        
    total_rewards.append(current_reward)

thousand_rewards = np.split(np.array(total_rewards), episodes/1000)
count = 1000
print("Average reward per 1000 episodes \n")
for i in thousand_rewards:
    print("{} : {}".format(count, str(sum(i/1000))))
    count += 1000

print("\nQ-table\n")
print(q_table)

Average reward per 1000 episodes 

1000 : 0.04100000000000003
2000 : 0.20900000000000016
3000 : 0.3930000000000003
4000 : 0.5540000000000004
5000 : 0.6270000000000004
6000 : 0.6800000000000005
7000 : 0.6810000000000005
8000 : 0.6810000000000005
9000 : 0.6780000000000005
10000 : 0.6810000000000005

Q-table

[[0.52253406 0.49635275 0.50075802 0.50236937]
 [0.36828298 0.36039708 0.29091153 0.48905242]
 [0.4197704  0.41335659 0.40530025 0.4575074 ]
 [0.2815233  0.3275609  0.25634037 0.43765137]
 [0.5406537  0.42853779 0.24513953 0.30034074]
 [0.         0.         0.         0.        ]
 [0.25208092 0.13853044 0.16005061 0.17521661]
 [0.         0.         0.         0.        ]
 [0.42416248 0.22004048 0.41392397 0.5743945 ]
 [0.56780605 0.62938432 0.40684659 0.34548721]
 [0.58557402 0.40116357 0.4215965  0.41904593]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.5793996  0.58352625 0.7562286  0.45505909]
 [0.75182682 0.89725078 0.78223265